# GEOG 592 — Module 3 Homework, Pandas Intro
Hailey Rodriguez

Using the cleaned CSV file from the previous homework, create a Jupyter Notebook that opens and explores the data using pandas.

Use the following methods:

df.head()

df.shape

df.columns

df.dtypes

df.info()

Also use a mask to create a dataframe with less rows. 

Upload the JN to homework/week04

Input the link of your GitHub JN in Canvas. Do not use AI for this HW.

In [4]:
import pandas as pd

print(pd.__version__)

3.0.5

### Read a CSV into a DataFrame

In [6]:
filename = "scdnr_species_county_clean.csv"
df = pd.read_csv(filename)

In [7]:
type(df)

pandas.DataFrame

In [8]:
df.head()

,record_id,county,scientific_name,s_common_name,inf_taxon,group_member_type_desc,g_rank,s_rank,g1g2s1s2,state_status,...,swap_priority_desc,presence_status,obsrank,locuseclass,date_class,first_obs_date,last_survey_date,dateconvert,count_records,eo_id_sc
0,1,Abbeville,Alasmidonta varicosa,Brook Floater,Freshwater Mussels,Zoological,G3,S1S2,1,Not Applicable,...,Highest,3,N - Not Ranked,Not applicable,> 40 Years,1960-09-04,1960-09-04,1960-09-04,81,15820
1,2,Abbeville,Ameiurus brunneus,Snail Bullhead,"Fishes - Freshwater and Anadromous Bony, Carti...",Zoological,G4,S3S4,1,Not Applicable,...,Moderate,3,N - Not Ranked,Not applicable,5 - 10 Years,2016-07-27,2016-07-27,2016-07-27,81,18664
2,16,Abbeville,Ameiurus catus,White Catfish,"Fishes - Freshwater and Anadromous Bony, Carti...",Zoological,G5,S4,1,Not Applicable,...,Moderate,3,N - Not Ranked,Not applicable,> 40 Years,1973-08-10,1976-06-21,1976-06-21,81,12076
3,31,Abbeville,Ameiurus platycephalus,Flat Bullhead,"Fishes - Freshwater and Anadromous Bony, Carti...",Zoological,G4,S3S4,1,Not Applicable,...,Moderate,3,E - Verified extant (viability not assessed),Not applicable,< 5 Years,1974-06-13,2022-06-21,2022-06-21,81,12325
4,79,Abbeville,Ammodramus savannarum,Grasshopper Sparrow,Birds,Zoological,G5,S3,1,Not Applicable,...,Highest,3,N - Not Ranked,Breeding,20 - 40 Years,1993,1993,1993,81,25906

In [9]:
df.shape

(6743, 25)

In [10]:
df.columns

Index(['record_id', 'county', 'scientific_name', 's_common_name', 'inf_taxon',
       'group_member_type_desc', 'g_rank', 's_rank', 'g1g2s1s2',
       'state_status', 'state_protect_status_desc', 'fed_status',
       'fed_protect_desc', 'listed_species', 'tracked_species',
       'swap_priority_desc', 'presence_status', 'obsrank', 'locuseclass',
       'date_class', 'first_obs_date', 'last_survey_date', 'dateconvert',
       'count_records', 'eo_id_sc'],
      dtype='str')

In [11]:
df.dtypes

record_id                    int64
county                         str
scientific_name                str
s_common_name                  str
inf_taxon                      str
group_member_type_desc         str
g_rank                         str
s_rank                         str
g1g2s1s2                     int64
state_status                   str
state_protect_status_desc      str
fed_status                     str
fed_protect_desc               str
listed_species               int64
tracked_species              int64
swap_priority_desc             str
presence_status              int64
obsrank                        str
locuseclass                    str
date_class                     str
first_obs_date                 str
last_survey_date               str
dateconvert                    str
count_records                int64
eo_id_sc                     int64
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6743 entries, 0 to 6742
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   record_id                  6743 non-null   int64
 1   county                     6743 non-null   str
 2   scientific_name            6743 non-null   str
 3   s_common_name              6743 non-null   str
 4   inf_taxon                  6743 non-null   str
 5   group_member_type_desc     6743 non-null   str
 6   g_rank                     6743 non-null   str
 7   s_rank                     6743 non-null   str
 8   g1g2s1s2                   6743 non-null   int64
 9   state_status               6743 non-null   str
 10  state_protect_status_desc  6743 non-null   str
 11  fed_status                 6743 non-null   str
 12  fed_protect_desc           6743 non-null   str
 13  listed_species             6743 non-null   int64
 14  tracked_species            6743 non-null   int64
 15  swap_priority_desc         6743 non-null   str
 16  presence_status            6743 non-null   int64
 17  obsrank                    6743 non-null   str
 18  locuseclass                6743 non-null   str
 19  date_class                 6743 non-null   str
 20  first_obs_date             6743 non-null   str
 21  last_survey_date           6743 non-null   str
 22  dateconvert                6743 non-null   str
 23  count_records              6743 non-null   int64
 24  eo_id_sc                   6743 non-null   int64
dtypes: int64(7), str(18)
memory usage: 1.3 MB

In [13]:
mask = df['county'].str.startswith('A', na=False)
df2 =df[mask]
df2

,record_id,county,scientific_name,s_common_name,inf_taxon,group_member_type_desc,g_rank,s_rank,g1g2s1s2,state_status,...,swap_priority_desc,presence_status,obsrank,locuseclass,date_class,first_obs_date,last_survey_date,dateconvert,count_records,eo_id_sc
0,1,Abbeville,Alasmidonta varicosa,Brook Floater,Freshwater Mussels,Zoological,G3,S1S2,1,Not Applicable,...,Highest,3,N - Not Ranked,Not applicable,> 40 Years,1960-09-04,1960-09-04,1960-09-04,81,15820
1,2,Abbeville,Ameiurus brunneus,Snail Bullhead,"Fishes - Freshwater and Anadromous Bony, Carti...",Zoological,G4,S3S4,1,Not Applicable,...,Moderate,3,N - Not Ranked,Not applicable,5 - 10 Years,2016-07-27,2016-07-27,2016-07-27,81,18664
2,16,Abbeville,Ameiurus catus,White Catfish,"Fishes - Freshwater and Anadromous Bony, Carti...",Zoological,G5,S4,1,Not Applicable,...,Moderate,3,N - Not Ranked,Not applicable,> 40 Years,1973-08-10,1976-06-21,1976-06-21,81,12076
3,31,Abbeville,Ameiurus platycephalus,Flat Bullhead,"Fishes - Freshwater and Anadromous Bony, Carti...",Zoological,G4,S3S4,1,Not Applicable,...,Moderate,3,E - Verified extant (viability not assessed),Not applicable,< 5 Years,1974-06-13,2022-06-21,2022-06-21,81,12325
4,79,Abbeville,Ammodramus savannarum,Grasshopper Sparrow,Birds,Zoological,G5,S3,1,Not Applicable,...,Highest,3,N - Not Ranked,Breeding,20 - 40 Years,1993,1993,1993,81,25906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,4967,Anderson,Terrapene carolina,Eastern Box Turtle,Turtles,Zoological,G5,S3,1,R: Regulated,...,Moderate,3,E - Verified extant (viability not assessed),Not applicable,< 5 Years,2023-08-24 17:17,2023-08-24 17:17,2023-08-24 17:17,80,23793
542,4970,Anderson,Trillium rugelii,Southern Nodding Trillium,Monocots,Botanical,G4,S2,1,Not Applicable,...,High,3,N - Not Ranked,Not Recorded,> 40 Years,1975-04-11,1975-04-11,1975-04-11,80,5193
543,4971,Anderson,Tyto alba,Barn Owl,Birds,Zoological,G5,S3,1,Not Applicable,...,Moderate,3,N - Not Ranked,Nonbreeding,20 - 40 Years,1989-06-23,2004-06-04,2004-06-04,80,2784
544,4974,Anderson,Viola tripartita,Three-parted Violet,Dicots,Botanical,G5T3,S3?,1,Not Applicable,...,Not Applicable,3,N - Not Ranked,Not Recorded,> 40 Years,1984-08-02,1984-08-02,1984-08-02,80,4619
545,4979,Anderson,Waterbird Colony,Waterbird Colony,Birds,Zoological,GNR,S3,1,Not Applicable,...,Not Applicable,3,N - Not Ranked,Not Recorded,20 - 40 Years,2000-03-15,2000-03-15,2000-03-15,80,21355