# GEOG 592 – Module 4: NumPy Practice Sheet

Review how indexing changes as we move from Python lists, to pandas objects, to NumPy arrays. Answers were written without running the code first; each code cell below checks the answer.

## Python indexing refresher

In [1]:
locations = ["Oak", "Pine", "Maple", "Cedar", "Elm"]

**1. What value is returned by `locations[0]`?**

*My answer:* Oak

In [2]:
locations[0]

'Oak'

**2. What value is returned by `locations[4]`?**

*My answer:* Elm

In [3]:
locations[4]

'Elm'

**3. What values are returned by `locations[1:4]`?**

*My answer:* Pine, Maple, Cedar

In [4]:
locations[1:4]

['Pine', 'Maple', 'Cedar']

**4. Write an indexing expression that returns `"Maple"`.**

*My answer:* `locations[2]`

In [5]:
locations[2]

'Maple'

In [6]:
points = [[100, 200], [140, 230], [180, 260], [120, 280]]

**5. What does `points[2]` return?**

*My answer:* [180, 260]

In [7]:
points[2]

[180, 260]

**6. What does `points[2][1]` return? Explain what each index selects.**

*My answer:* 260. `[2]` selects the third point, `[1]` selects its y value.

In [8]:
points[2][1]

260

**7. Write an expression that returns the x-coordinate of the second point. Assume the coordinates are stored as [x, y].**

*My answer:* `points[1][0]`

In [9]:
points[1][0]

140

## pandas indexing refresher

In [10]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Oak", "Pine", "Maple", "Cedar"],
    "ft": [25, 48, 31, 60],
    "zone": ["A", "B", "A", "B"]
})
df

    name  ft zone
0    Oak  25    A
1   Pine  48    B
2  Maple  31    A
3  Cedar  60    B

**8. What type of object is returned by `df["ft"]`?**

*My answer:* Series

In [11]:
type(df["ft"])

pandas.Series

**9. Write code to select the name and ft columns together.**

*My answer:* `df[["name", "ft"]]`

In [12]:
df[["name", "ft"]]

    name  ft
0    Oak  25
1   Pine  48
2  Maple  31
3  Cedar  60

**10. What row is returned by `df.iloc[1]`?**

*My answer:* Pine, 48, B

In [13]:
df.iloc[1]

name    Pine
ft        48
zone       B
Name: 1, dtype: object

**11. Write code using iloc to select the first three rows.**

*My answer:* `df.iloc[0:3]`

In [14]:
df.iloc[0:3]

    name  ft zone
0    Oak  25    A
1   Pine  48    B
2  Maple  31    A

**12. Write code to select rows where ft is greater than 30.**

*My answer:* `df[df["ft"] > 30]`

In [15]:
df[df["ft"] > 30]

    name  ft zone
1   Pine  48    B
2  Maple  31    A
3  Cedar  60    B

**13. What rows are returned by `df.iloc[1:3]`?**

*My answer:* Pine, 48, B and Maple (31, A)

In [16]:
df.iloc[1:3]

    name  ft zone
1   Pine  48    B
2  Maple  31    A

## Moving to NumPy arrays

In [17]:
import numpy as np

points = np.array([
    [100, 200],
    [140, 230],
    [180, 260],
    [120, 280]
])

**14. What does `points.shape` return, and what do the two numbers mean?**

*My answer:* (4, 2). 4 is rows and 2 is columns.

In [18]:
points.shape

(4, 2)

**15. What does `points[0]` return?**

*My answer:* 100, 200

In [19]:
points[0]

array([100, 200])

**16. What does `points[0, 1]` return?**

*My answer:* 200

In [20]:
points[0, 1]

np.int64(200)

**17. What does `points[:, 0]` return? Explain the colon.**

*My answer:* 100, 140, 180, 120. `:` means all rows, so this returns column 0 (x values).

In [21]:
points[:, 0]

array([100, 140, 180, 120])

**18. What does `points[:, 1]` return?**

*My answer:* 200, 230, 260, 280

In [22]:
points[:, 1]

array([200, 230, 260, 280])

**19. Write NumPy indexing code that returns the second and third rows.**

*My answer:* `points[1:3]`

In [23]:
points[1:3]

array([[140, 230],
       [180, 260]])

**20. Compare `points[2][1]` with `points[2, 1]`.**

*My answer:* `[2][1]` takes 2 steps, pulling out the 3rd row then indexing it for the y value; `[2, 1]` goes straight to row 2, column 1. Both pull 260.

In [24]:
print(points[2][1])
print(points[2, 1])

260
260

## Vectorized operations

In [25]:
shift = np.array([10, 20])

**21. Without running the code, determine the result of `points + shift`.**

*My answer:* [110, 220], [150, 250], [190, 280], [130, 300]

In [26]:
points + shift

array([[110, 220],
       [150, 250],
       [190, 280],
       [130, 300]])

**22. Why does this operation not require a Python for loop?**

*My answer:* np.array tells the code to do the adding of 10 to x and 20 to y for the whole array.

## Boolean masks and spatial queries

In [27]:
x = points[:, 0]
y = points[:, 1]

inside = (x >= 110) & (x <= 150) & (y >= 220) & (y <= 290)

**23. Write the Boolean values stored in `inside[:]`.**

*My answer:* [False, True, False, True]

In [28]:
inside[:]

array([False,  True, False,  True])

**24. What does `points[inside]` return?**

*My answer:* [[140, 230], [120, 280]]

In [29]:
points[inside]

array([[140, 230],
       [120, 280]])

**25. In GIS language, what spatial operation is this Boolean mask approximating?**

*My answer:* A select bounding-box query that keeps the points inside a rectangle.

## np.where() and classification

In [30]:
elevation = np.array([240, 510, 430, 680])
classes = np.where(elevation >= 500, 1, 0)

**26. What values are stored in `classes[:]`?**

*My answer:* [0, 1, 0, 1]

In [31]:
classes[:]

array([0, 1, 0, 1])

**27. In your own words, explain the three arguments in `np.where(condition, value_if_true, value_if_false)`.**

*My answer:* Condition checks for the element, value_if_true is used to decide output when the test is true, and value_if_false does the same for when it's false.

## Distance and pandas connection

In [32]:
a = np.array([100, 200])
b = np.array([140, 230])
distance = np.sqrt(((a - b) ** 2).sum())

**28. What does `a - b` return?**

*My answer:* -40, -30

In [33]:
a - b

array([-40, -30])

**29. Explain why this calculation is an example of vectorized arithmetic: `distance = np.sqrt(((a - b) ** 2).sum())`**

*My answer:* The subtraction, squaring and sum apply to the whole array at once without a loop.

In [34]:
distance

np.float64(50.0)

In [35]:
ft_array = df["ft"].to_numpy()

**30. What type of object is `ft_array`?**

*My answer:* numpy.ndarray

In [36]:
type(ft_array)

numpy.ndarray

**31. What happened to the pandas index and column label when the Series was converted to NumPy?**

*My answer:* Both are dropped and only the values are left without the index or label.

In [37]:
ft_array

array([25, 48, 31, 60])

## Big picture

**32. Complete the table by describing what is being selected.**

| Structure | Expression | What it selects |
|---|---|---|
| Python list | `locations[2]` | Maple |
| Nested Python list | `points_list[2][1]` | 260 |
| pandas DataFrame | `df.iloc[2, 1]` | 31 |
| NumPy array | `points[2, 1]` | 260 |
| NumPy array | `points[:, 0]` | 100, 140, 180, 120 |

In [38]:
points_list = [[100, 200], [140, 230], [180, 260], [120, 280]]

print(locations[2])
print(points_list[2][1])
print(df.iloc[2, 1])
print(points[2, 1])
print(points[:, 0])

Maple
260
31
260
[100 140 180 120]

**33. In one sentence: what is the main indexing idea that stays the same across Python, pandas, and NumPy?**

*My answer:* Indexing is position-based and starts at 0; the first index pulls the row and the second pulls the column.

**34. What becomes easier when data are arranged as a 2-D NumPy array?**

*My answer:* It becomes quicker to code what you need to rather than writing out every step, by grabbing whole rows/columns.